const fs = require('fs');
const path = require('path');
require('dotenv').config();

const configTemplate = `// ═══════════════════════════════════════════════════════════
// Supabase Configuration — HimawariDigi Live Chat
// ═══════════════════════════════════════════════════════════
// This file is auto-generated by scripts/build-env.js
// DO NOT edit this file directly. Edit the .env file instead.

(function () {
  'use strict';

  // ── Supabase Config ───────────────────────────────────────
  const SUPABASE_URL = "${process.env.SUPABASE_URL || ''}";
  const SUPABASE_ANON_KEY = "${process.env.SUPABASE_ANON_KEY || ''}";

  if (typeof supabase === 'undefined') {
    console.error("Supabase UMD is not loaded! Check script tags.");
  } else {
    window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  }

  // ── CS App Config ─────────────────────────────────────────
  window.CS_EMAIL = "${process.env.CS_EMAIL || 'himawaridigi@gmail.com'}";

  // ── Shared Utilities ──────────────────────────────────────

  /** Escape HTML to prevent XSS */
  window.chatSanitize = function (str) {
    const div = document.createElement('div');
    div.appendChild(document.createTextNode(str));
    return div.innerHTML;
  };

  /** Format timestamp to relative time (ID locale) */
  window.chatRelativeTime = function (ts) {
    const now = Date.now();
    const diff = now - ts;
    const sec = Math.floor(diff / 1000);
    const min = Math.floor(sec / 60);
    const hr = Math.floor(min / 60);
    const day = Math.floor(hr / 24);

    if (sec < 60) return 'Baru saja';
    if (min < 60) return min + ' menit lalu';
    if (hr < 24) return hr + ' jam lalu';
    if (day < 7) return day + ' hari lalu';
    return new Date(ts).toLocaleDateString('id-ID', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
    });
  };

  /** Format timestamp to time string HH:MM */
  window.chatFormatTime = function (ts) {
    return new Date(ts).toLocaleTimeString('id-ID', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    });
  };

  /** Generate or retrieve persistent device ID */
  window.getDeviceId = function () {
    let id = localStorage.getItem('hd_device_id');
    if (!id) {
      id =
        'dev_' +
        Date.now().toString(36) +
        '_' +
        Math.random().toString(36).substring(2, 9);
      localStorage.setItem('hd_device_id', id);
    }
    return id;
  };

  /** Parse user agent to readable device string */
  window.parseDeviceInfo = function () {
    const ua = navigator.userAgent;
    let browser = 'Unknown Browser';
    let os = 'Unknown OS';

    if (ua.includes('Firefox/')) browser = 'Firefox';
    else if (ua.includes('Edg/')) browser = 'Microsoft Edge';
    else if (ua.includes('Chrome/')) browser = 'Chrome';
    else if (ua.includes('Safari/')) browser = 'Safari';
    else if (ua.includes('Opera/') || ua.includes('OPR/')) browser = 'Opera';

    if (ua.includes('Windows NT 10')) os = 'Windows 10/11';
    else if (ua.includes('Windows')) os = 'Windows';
    else if (ua.includes('Mac OS X')) os = 'macOS';
    else if (ua.includes('Android')) os = 'Android';
    else if (ua.includes('iPhone') || ua.includes('iPad')) os = 'iOS';
    else if (ua.includes('Linux')) os = 'Linux';

    return { browser, os, full: browser + ' · ' + os };
  };

  /** Play notification sound via MP3 */
  window.playNotifSound = function () {
    try {
      const audio = new Audio('/assets/notification_alert.mp3');
      audio.play().catch(e => {
        // Fallback to beep if browser blocks autoplay before user interaction
        const ctx = new (window.AudioContext || window.webkitAudioContext)();
        const osc = ctx.createOscillator();
        const gain = ctx.createGain();
        osc.connect(gain);
        gain.connect(ctx.destination);
        osc.frequency.value = 880;
        osc.type = 'sine';
        gain.gain.setValueAtTime(0.15, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.4);
        osc.start(ctx.currentTime);
        osc.stop(ctx.currentTime + 0.4);
      });
    } catch (e) {
      /* silent fail */
    }
  };

  /** Compress Image using Canvas API */
  window.compressImageFile = function (file, maxWidth = 1200, quality = 0.8) {
    return new Promise((resolve, reject) => {
      if (!file.type.startsWith('image/')) {
        return resolve(file); // Not an image, return original
      }
      // Don't compress SVGs or GIFs as it might ruin them or animation
      if (file.type === 'image/svg+xml' || file.type === 'image/gif') {
        return resolve(file);
      }

      const img = new Image();
      const url = URL.createObjectURL(file);

      img.onload = () => {
        URL.revokeObjectURL(url);

        let width = img.width;
        let height = img.height;

        if (width > maxWidth) {
          height = Math.round((height * maxWidth) / width);
          width = maxWidth;
        }

        const canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = height;

        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0, width, height);

        // Preserve PNG transparency; convert others to JPEG
        const outType = file.type === 'image/png' ? 'image/png' : (file.type === 'image/webp' ? 'image/webp' : 'image/jpeg');
        const outExt = outType === 'image/png' ? '.png' : (outType === 'image/webp' ? '.webp' : '.jpg');

        canvas.toBlob((blob) => {
          if (!blob) return reject(new Error('Canvas toBlob failed'));
          // Re-create a File object
          const newFile = new File([blob], file.name.replace(/\\.[^/.]+$/, "") + outExt, {
            type: outType,
            lastModified: Date.now()
          });
          resolve(newFile);
        }, outType, quality);
      };

      img.onerror = () => reject(new Error('Failed to load image for compression'));
      img.src = url;
    });
  };

  // ── Push Notification Trigger ─────────────────────────────
  // Memanggil Supabase Edge Function "send-push" setelah pesan dikirim.
  window.triggerPushNotification = async function (messageData) {
    try {
      const resp = await fetch(SUPABASE_URL + '/functions/v1/send-push', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': 'Bearer ' + SUPABASE_ANON_KEY,
        },
        body: JSON.stringify({ record: messageData }),
      });
      const respText = await resp.text();
      console.log('[Push] Response:', resp.status, respText);
    } catch (e) {
      console.error('[Push] Error:', e);
    }
  };
  // ── Custom Audio Player Global Functions ────────────────
  window.hdToggleAudio = function(btn) {
    const player = btn.closest('.hd-audio-player');
    const audio = player.querySelector('.hd-audio-element');
    const icon = btn.querySelector('i');

    // Pause all other audio
    document.querySelectorAll('.hd-audio-element').forEach(a => {
      if (a !== audio && !a.paused) {
        a.pause();
        const otherBtn = a.closest('.hd-audio-player').querySelector('.hd-audio-play-btn i');
        if(otherBtn) otherBtn.className = 'ph-fill ph-play';
      }
    });

    if (audio.paused) {
      audio.play();
      icon.className = 'ph-fill ph-pause';
    } else {
      audio.pause();
      icon.className = 'ph-fill ph-play';
    }
  };

  window.hdSeekAudio = function(slider) {
    const player = slider.closest('.hd-audio-player');
    const audio = player.querySelector('.hd-audio-element');
    if (audio.duration) {
      audio.currentTime = (slider.value / 100) * audio.duration;
    }
  };

  window.hdFormatAudioTime = function(sec) {
    if (isNaN(sec) || !isFinite(sec)) return '0:00';
    const m = Math.floor(sec / 60);
    const s = Math.floor(sec % 60);
    return m + ':' + (s < 10 ? '0'+s : s);
  };

  window.bindAudioPlayers = function() {
    document.querySelectorAll('.hd-audio-element:not(.bound)').forEach(audio => {
      audio.classList.add('bound');
      const player = audio.closest('.hd-audio-player');
      if (!player) return;
      const fill = player.querySelector('.hd-audio-progress-fill');
      const slider = player.querySelector('.hd-audio-progress-slider');
      const timeDisplay = player.querySelector('.hd-audio-time');

      audio.addEventListener('loadedmetadata', () => {
        timeDisplay.textContent = window.hdFormatAudioTime(audio.duration);
      });
      audio.addEventListener('timeupdate', () => {
        const percent = (audio.currentTime / audio.duration) * 100 || 0;
        fill.style.width = percent + '%';
        slider.value = percent;
        timeDisplay.textContent = window.hdFormatAudioTime(audio.currentTime);
      });
      audio.addEventListener('ended', () => {
        const icon = player.querySelector('.hd-audio-play-btn i');
        if(icon) icon.className = 'ph-fill ph-play';
        fill.style.width = '0%';
        slider.value = 0;
        timeDisplay.textContent = window.hdFormatAudioTime(audio.duration);
      });
    });
  };

  // MutationObserver to auto-bind new audio players as they are injected
  const hdAudioObserver = new MutationObserver((mutations) => {
    let hasNewAudio = false;
    for (const m of mutations) {
      if (m.addedNodes.length > 0) {
        hasNewAudio = true;
        break;
      }
    }
    if (hasNewAudio) {
      window.bindAudioPlayers();
    }
  });
  if (typeof document !== 'undefined') {
    hdAudioObserver.observe(document.body, { childList: true, subtree: true });
    // Bind initial
    setTimeout(() => window.bindAudioPlayers(), 500);
  }

})();
`;

const targetPath = path.join(__dirname, '../js/supabase-config.js');
fs.writeFileSync(targetPath, configTemplate);

console.log('✅ Generated js/supabase-config.js from .env variables');
