const fs = require('fs');
const path = require('path');
require('dotenv').config();

const configTemplate = `// ═══════════════════════════════════════════════════════════
// Firebase + EmailJS Configuration — HimawariDigi Live Chat
// ═══════════════════════════════════════════════════════════
// This file is auto-generated by scripts/build-env.js
// DO NOT edit this file directly. Edit the .env file instead.

(function () {
  'use strict';

  // ── Firebase Config ───────────────────────────────────────
  const firebaseConfig = {
    apiKey: "${process.env.FIREBASE_API_KEY || ''}",
    authDomain: "${process.env.FIREBASE_AUTH_DOMAIN || ''}",
    databaseURL: "${process.env.FIREBASE_DATABASE_URL || ''}",
    projectId: "${process.env.FIREBASE_PROJECT_ID || ''}",
    storageBucket: "${process.env.FIREBASE_STORAGE_BUCKET || ''}",
    messagingSenderId: "${process.env.FIREBASE_MESSAGING_SENDER_ID || ''}",
    appId: "${process.env.FIREBASE_APP_ID || ''}",
    measurementId: "${process.env.FIREBASE_MEASUREMENT_ID || ''}"
  };

  if (!firebase.apps.length) {
    firebase.initializeApp(firebaseConfig);
  }

  window.firebaseDB = firebase.database();

  // ── EmailJS Config ────────────────────────────────────────
  window.EMAILJS_CONFIG = {
    serviceId: "${process.env.EMAILJS_SERVICE_ID || ''}",
    templateId: "${process.env.EMAILJS_TEMPLATE_ID || ''}",
    publicKey: "${process.env.EMAILJS_PUBLIC_KEY || ''}",
    recipientEmail: "${process.env.EMAILJS_RECIPIENT_EMAIL || 'himawaridigi@gmail.com'}",
  };

  // Initialize EmailJS
  if (typeof emailjs !== 'undefined') {
    emailjs.init(window.EMAILJS_CONFIG.publicKey);
  }

  // ── Shared Utilities ──────────────────────────────────────

  /** Escape HTML to prevent XSS */
  window.chatSanitize = function (str) {
    const div = document.createElement('div');
    div.appendChild(document.createTextNode(str));
    return div.innerHTML;
  };

  /** Format timestamp to relative time (ID locale) */
  window.chatRelativeTime = function (ts) {
    const now = Date.now();
    const diff = now - ts;
    const sec = Math.floor(diff / 1000);
    const min = Math.floor(sec / 60);
    const hr = Math.floor(min / 60);
    const day = Math.floor(hr / 24);

    if (sec < 60) return 'Baru saja';
    if (min < 60) return min + ' menit lalu';
    if (hr < 24) return hr + ' jam lalu';
    if (day < 7) return day + ' hari lalu';
    return new Date(ts).toLocaleDateString('id-ID', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
    });
  };

  /** Format timestamp to time string HH:MM */
  window.chatFormatTime = function (ts) {
    return new Date(ts).toLocaleTimeString('id-ID', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    });
  };

  /** Generate or retrieve persistent device ID */
  window.getDeviceId = function () {
    let id = localStorage.getItem('hd_device_id');
    if (!id) {
      id =
        'dev_' +
        Date.now().toString(36) +
        '_' +
        Math.random().toString(36).substring(2, 9);
      localStorage.setItem('hd_device_id', id);
    }
    return id;
  };

  /** Parse user agent to readable device string */
  window.parseDeviceInfo = function () {
    const ua = navigator.userAgent;
    let browser = 'Unknown Browser';
    let os = 'Unknown OS';

    if (ua.includes('Firefox/')) browser = 'Firefox';
    else if (ua.includes('Edg/')) browser = 'Microsoft Edge';
    else if (ua.includes('Chrome/')) browser = 'Chrome';
    else if (ua.includes('Safari/')) browser = 'Safari';
    else if (ua.includes('Opera/') || ua.includes('OPR/')) browser = 'Opera';

    if (ua.includes('Windows NT 10')) os = 'Windows 10/11';
    else if (ua.includes('Windows')) os = 'Windows';
    else if (ua.includes('Mac OS X')) os = 'macOS';
    else if (ua.includes('Android')) os = 'Android';
    else if (ua.includes('iPhone') || ua.includes('iPad')) os = 'iOS';
    else if (ua.includes('Linux')) os = 'Linux';

    return { browser, os, full: browser + ' · ' + os };
  };

  /** Play notification sound via Web Audio API */
  window.playNotifSound = function () {
    try {
      const ctx = new (window.AudioContext || window.webkitAudioContext)();
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();
      osc.connect(gain);
      gain.connect(ctx.destination);
      osc.frequency.value = 880;
      osc.type = 'sine';
      gain.gain.setValueAtTime(0.15, ctx.currentTime);
      gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.4);
      osc.start(ctx.currentTime);
      osc.stop(ctx.currentTime + 0.4);
    } catch (e) {
      /* silent fail */
    }
  };

  console.log('🔥 HimawariDigi Chat — Firebase initialized');
})();
`;

const targetPath = path.join(__dirname, '../js/firebase-config.js');
fs.writeFileSync(targetPath, configTemplate);

console.log('✅ Generated js/firebase-config.js from .env variables');
