const fs = require('fs');
const path = require('path');
require('dotenv').config();

const configTemplate = `// ═══════════════════════════════════════════════════════════
// Supabase Configuration — HimawariDigi Live Chat
// ═══════════════════════════════════════════════════════════
// This file is auto-generated by scripts/build-env.js
// DO NOT edit this file directly. Edit the .env file instead.

(function () {
  'use strict';

  // ── Supabase Config ───────────────────────────────────────
  const SUPABASE_URL = "${process.env.SUPABASE_URL || ''}";
  const SUPABASE_ANON_KEY = "${process.env.SUPABASE_ANON_KEY || ''}";

  if (typeof supabase === 'undefined') {
    console.error("Supabase UMD is not loaded! Check script tags.");
  } else {
    window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
  }

  // ── CS App Config ─────────────────────────────────────────
  window.CS_EMAIL = "${process.env.CS_EMAIL || 'himawaridigi@gmail.com'}";

  // ── Shared Utilities ──────────────────────────────────────

  /** Escape HTML to prevent XSS */
  window.chatSanitize = function (str) {
    const div = document.createElement('div');
    div.appendChild(document.createTextNode(str));
    return div.innerHTML;
  };

  /** Format timestamp to relative time (ID locale) */
  window.chatRelativeTime = function (ts) {
    const now = Date.now();
    const diff = now - ts;
    const sec = Math.floor(diff / 1000);
    const min = Math.floor(sec / 60);
    const hr = Math.floor(min / 60);
    const day = Math.floor(hr / 24);

    if (sec < 60) return 'Baru saja';
    if (min < 60) return min + ' menit lalu';
    if (hr < 24) return hr + ' jam lalu';
    if (day < 7) return day + ' hari lalu';
    return new Date(ts).toLocaleDateString('id-ID', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
    });
  };

  /** Format timestamp to time string HH:MM */
  window.chatFormatTime = function (ts) {
    return new Date(ts).toLocaleTimeString('id-ID', {
      hour: '2-digit',
      minute: '2-digit',
      hour12: false,
    });
  };

  /** Generate or retrieve persistent device ID */
  window.getDeviceId = function () {
    let id = localStorage.getItem('hd_device_id');
    if (!id) {
      id =
        'dev_' +
        Date.now().toString(36) +
        '_' +
        Math.random().toString(36).substring(2, 9);
      localStorage.setItem('hd_device_id', id);
    }
    return id;
  };

  /** Parse user agent to readable device string */
  window.parseDeviceInfo = function () {
    const ua = navigator.userAgent;
    let browser = 'Unknown Browser';
    let os = 'Unknown OS';

    if (ua.includes('Firefox/')) browser = 'Firefox';
    else if (ua.includes('Edg/')) browser = 'Microsoft Edge';
    else if (ua.includes('Chrome/')) browser = 'Chrome';
    else if (ua.includes('Safari/')) browser = 'Safari';
    else if (ua.includes('Opera/') || ua.includes('OPR/')) browser = 'Opera';

    if (ua.includes('Windows NT 10')) os = 'Windows 10/11';
    else if (ua.includes('Windows')) os = 'Windows';
    else if (ua.includes('Mac OS X')) os = 'macOS';
    else if (ua.includes('Android')) os = 'Android';
    else if (ua.includes('iPhone') || ua.includes('iPad')) os = 'iOS';
    else if (ua.includes('Linux')) os = 'Linux';

    return { browser, os, full: browser + ' · ' + os };
  };

  /** Play notification sound via MP3 */
  window.playNotifSound = function () {
    try {
      const audio = new Audio('/assets/notification_alert.mp3');
      audio.play().catch(e => {
        // Fallback to beep if browser blocks autoplay before user interaction
        const ctx = new (window.AudioContext || window.webkitAudioContext)();
        const osc = ctx.createOscillator();
        const gain = ctx.createGain();
        osc.connect(gain);
        gain.connect(ctx.destination);
        osc.frequency.value = 880;
        osc.type = 'sine';
        gain.gain.setValueAtTime(0.15, ctx.currentTime);
        gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.4);
        osc.start(ctx.currentTime);
        osc.stop(ctx.currentTime + 0.4);
      });
    } catch (e) {
      /* silent fail */
    }
  };

  /** Compress Image using Canvas API */
  window.compressImageFile = function (file, maxWidth = 1200, quality = 0.8) {
    return new Promise((resolve, reject) => {
      if (!file.type.startsWith('image/')) {
        return resolve(file); // Not an image, return original
      }
      // Don't compress SVGs or GIFs as it might ruin them or animation
      if (file.type === 'image/svg+xml' || file.type === 'image/gif') {
        return resolve(file);
      }

      const img = new Image();
      const url = URL.createObjectURL(file);
      
      img.onload = () => {
        URL.revokeObjectURL(url);
        
        let width = img.width;
        let height = img.height;
        
        if (width > maxWidth) {
          height = Math.round((height * maxWidth) / width);
          width = maxWidth;
        }

        const canvas = document.createElement('canvas');
        canvas.width = width;
        canvas.height = height;
        
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0, width, height);
        
        // Preserve PNG transparency; convert others to JPEG
        const outType = file.type === 'image/png' ? 'image/png' : (file.type === 'image/webp' ? 'image/webp' : 'image/jpeg');
        const outExt = outType === 'image/png' ? '.png' : (outType === 'image/webp' ? '.webp' : '.jpg');
        
        canvas.toBlob((blob) => {
          if (!blob) return reject(new Error('Canvas toBlob failed'));
          // Re-create a File object
          const newFile = new File([blob], file.name.replace(/\\.[^/.]+$/, "") + outExt, {
            type: outType,
            lastModified: Date.now()
          });
          resolve(newFile);
        }, outType, quality);
      };
      
      img.onerror = () => reject(new Error('Failed to load image for compression'));
      img.src = url;
    });
  };

  console.log('🔥 HimawariDigi Chat — Supabase initialized');
})();
`;

const targetPath = path.join(__dirname, '../js/supabase-config.js');
fs.writeFileSync(targetPath, configTemplate);

console.log('✅ Generated js/supabase-config.js from .env variables');
